### ISSUE TITLE
Heroku setup

### ISSUE THREAD

**Issue by geekhubcode** [LeeChunHao2000/Cypto-TradingView-Webhook#1]
Hello! Thank you very much for your great work. I have 2 questions : Do you know how to deploy this on heroku? Are "sell signal" can be use to short or only exit long? Sorry if it is sound dumb I am not very expriment in coding. Thank you very much for your time and work. Best regards.

**Comment by LeeChunHao2000** [comment]
1. 
- You need to register an account with heroku first
- create an app
- set up the buildpack：

    `heroku/python`

- clone this repo, set up config.py and add Procfile file：

    `web: gunicorn app:app`

- push repo to your heroku app (file structure)：
![1626625328535](https://user-images.githubusercontent.com/64617939/126074742-a1d56c19-b7c6-4430-9f0d-2717369a670b.jpg)

- You can see ‘正常運作' at youappname.herukuapp.com if deploy success
- Set up your own signal with webhook on TradingView
- Enjoy your own tradingView Trading Bot

2.
- The operation is determine by what message you send via webhook
- Short is equal to exit long, both of them you need to send：

    `{"pair": "BTC-PERP", "side": "sell", "size": "0.01"}`

**Comment by LeeChunHao2000** [comment]
By the way, If you are not good at programming, https://trading.wunderbit.co/en will be another choice

**Comment by geekhubcode** [comment]
Hello Lee, thank you very much for your very good advice, time and fast reply:)

**Comment by LeeChunHao2000** [comment]
You're welcome:)

**Comment by geekhubcode** [comment]
Hello! When I push it to heroku, it's look like it's not seing the Procfile, I triple checked the format and it look fine and it is place at the roots of the folder, I tought may be it needs gunicorn in the requieremnts.txt but when I tried to add it, it's not loading in the app, like the requieremnts.txt is not read, I tought you could have a idea, thank in advance. Have a great day.

**Comment by LeeChunHao2000** [comment]
Oh, you need to add Procfile by yourself and the content in Profile file was like：

`web: gunicorn app:app`

Yes, you are right. Also need to add gunicorn in the equieremnts.txt.

**Comment by geekhubcode** [comment]
Thank you for your reply, yes I've done all of this but when I push it to heroku it is saying this "Procfile declares types -> (none)" as it should say "Procfile declares types -> (web)" also I notice that gunicorn is not loaded with flask and request when I push it even if I add it to requirement file. I've done it from scratch to make sure each time but same result. I might be wrong somewhere, thanks again for your help, I don't want to take too much of your time. Best regards.

**Comment by LeeChunHao2000** [comment]
Hi, Could you provide some screenshots about the error? I just push some setting in the repo need to pull again

Are you check buildpack here：
![1626706476159](https://user-images.githubusercontent.com/64617939/126181033-36055992-cb78-4c7c-a33b-d0a6ec054af8.jpg)

**Comment by geekhubcode** [comment]
Thank you so much for your help:) You can see: "Procfile declares types -> (none)" and the app won't load . I will check build pack, I will reinstall the app! 
![Capture d’écran 2021-07-19 à 17 42 52](https://user-images.githubusercontent.com/87607670/126187978-e8027040-e971-476b-84c5-020c0146683b.png)
Also on the last push I tried to add a "s" to requests in the requirements.txt
![Capture d’écran 2021-07-19 à 17 36 54](https://user-images.githubusercontent.com/87607670/126187292-03799724-5802-4849-9d70-859a5fc9de94.png)
![Capture d’écran 2021-07-19 à 17 36 32](https://user-images.githubusercontent.com/87607670/126187309-7eafa905-1b40-4680-a759-8b5ad23f645d.png)

**Comment by geekhubcode** [comment]
It works with the new package:) Thank you very much for taking the time to help me, that is very nice from you. Did you only change requirement.txt and add Procfile to the git or did you change something else?

**Comment by LeeChunHao2000** [comment]
You are welcome. Yes, I only changed requirement.txt and add Procfile.
